@startuml

entity "User" as U {
id: number <<generated>>
--
name: text
--
password: text
}

entity "Motorcycle" as M {
id: number <<generated>>
--
brand: text
--
model: text
--
year: text/number
}

entity "Registration" as R {
id: number <<generated>>
--
user_id: number <<foreign key>>
--
motorcycle_id: number <<foreign key>>
--
OPTIONAL -> date: timestamp
}

entity "Options" as O {
id: number <<generated>>
--
registration_id: number <<foreign key>>
--
description: text
}

entity "Service" as S {
id: number <<generated>>
--
registration_id: number <<foreign key>>
--
service_record_id: number <<foreign key>>
--
mileage: number
--
date: timestamp
}

entity "Default_Task" as DT {
id: number <<generated>>
--
description: text
--
interval_km: number
--
interval_months: number
}

entity "User_Task" as UT {
id: number <<generated>>
--
user_id: number <<foreign key>>
--
description: text
--
interval_km: number
--
interval_months: number
}

entity "Task" as T {
id: number <<generated>>
--
default_task_id: number <<foreign key>>
--
custom_task_id: number <<foreign key>>
--
CONSTRAINT: either motor/custom task id present
}

entity "Service_Record" as SR {
id: number <<generated>>
--
service_id: number <<foreign key>>
--
task_id: number <<foreign key>>
--
note: text
}

entity "Status" as SS  {
id: number <<generated>>
--
registration_id: number <<foreign key>>
--
task_id: number <<foreign key>>
--
next_service_km: number
--
next_service_months: number
}


U ||--|{ R
U ||--|{ UT
R }|--|| M
R ||--|{ S
R ||--|{ O
R ||--|{ SS
S ||--|{ SR
T }|--|| DT
T }|--|| UT
T }|--|{ SR
T ||--|{ SS

@enduml
